# /// script
# requires-python = ">=3.9"
# dependencies = []
# ///
"""
Scan all GPEC Fortran sources and emit the inter-object dependency graph
(an .o depends on another .o when it USEs a module that the other DEFINEs,
or INCLUDEs a file the other provides).

Module-name resolution respects each directory's -I search order taken from
RULES.inc, because module names collide across directories (dcon_mod,
local_mod, io_mod, gamma_mod, lar_mod, deltar_mod, debug_mod, resist_mod ...).
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))            # install/
REPO = os.path.dirname(ROOT)                                 # gpec/

# Directories scanned, in the build's declared order, with the extra source
# globs SOURCES.inc uses (vacuum adds *.c; xdraw is C-only / explicit).
FORT_EXT = (".f", ".f90", ".F", ".F90")

# Per-directory -I search path (besides the file's own dir), from RULES.inc.
# MATHINC / NETCDFINC are external; omitted.
INC_PATHS = {
    "equil":  [],
    "lsode":  ["equil"],
    "zlange": ["equil"],
    "zvode":  ["equil"],
    "orbit":  ["equil"],
    "vacuum": ["equil"],
    "pentrc": ["equil"],
    "dcon":   ["equil", "pentrc", "vacuum"],
    "rdcon":  ["equil", "vacuum"],
    "stride": ["equil", "vacuum"],
    "match":  ["equil"],
    "rmatch": ["equil"],
    "sum":    ["equil"],
    "multi":  ["equil"],
    "slayer": ["equil"],
    "coil":   ["equil"],
    "gpec":   ["equil", "vacuum", "pentrc", "coil", "slayer"],
}
DIR_ORDER = list(INC_PATHS.keys())

# Modules provided by compiler/runtime/external libs -> never a build dep.
EXTERNAL_MODULES = {
    "iso_c_binding", "iso_fortran_env", "ieee_arithmetic",
    "ieee_exceptions", "ieee_features",
    "omp_lib", "omp_lib_kinds", "mpi", "mpi_f08",
    "netcdf", "netcdf4", "netcdf_nf_interfaces", "ifport", "ifcore",
    "openacc", "cudafor",
}

# Generated include files: a source INCLUDEs them, but they are produced by a
# build rule (TARGETS.inc), so they do NOT exist in a clean checkout. The
# generic include handling below requires the file on disk; for these we must
# emit the dependency unconditionally, otherwise the .inc only appears when the
# generator happens to run on an already-built tree, and a clean run (CI) drops
# it -- causing parallel-build races (e.g. params.o before version.inc exists).
GENERATED_INCLUDES = {"version.inc"}

re_module  = re.compile(r"^\s*module\s+(\w+)", re.I)
re_endmod  = re.compile(r"^\s*end\s*module", re.I)
re_modproc = re.compile(r"^\s*module\s+procedure", re.I)
re_use     = re.compile(r"^\s*use\b\s*(?:,\s*intrinsic\s*)?(?:::)?\s*(\w+)", re.I)
re_inc     = re.compile(r"""^\s*include\s+['"]([^'"]+)['"]""", re.I)
re_cppinc  = re.compile(r"""^\s*\#\s*include\s+['"]([^'"]+)['"]""", re.I)

# Emitted verbatim at the top of DEPENDENCIES.inc. Keep this identical to the
# committed file's header so the generator is idempotent (see Emit comment).
HEADER = """\
#------------------------------------------------------------------------------
# DEPENDENCIES.inc
#
# Purpose:
#   Specifies dependencies between object files and modules.
#
# What it does:
#   - Ensures files and modules are built in the correct order
#   - Lists which object files depend on others (e.g. ../equil/grid.o depends
#     on ../equil/spline.o because grid.f does `USE spline_mod`)
#
# How to use:
#   - An object A.o must depend on B.o whenever A's source `USE`s a module that
#     B's source defines (the .mod must exist first) or `INCLUDE`s a file B
#     provides. Missing edges cause sporadic parallel-build (make -j) failures.
#   - This file is generated by ./gen_deps.py, which scans every Fortran source
#     for MODULE/USE/INCLUDE and resolves module names using each directory's
#     -I search order from RULES.inc (module names collide across directories,
#     e.g. dcon_mod, local_mod, io_mod, gamma_mod, debug_mod). After adding or
#     changing sources, regenerate with:  python gen_deps.py > DEPENDENCIES.inc
#   - Edges are direct dependencies only; transitive ones are implied by make.
#------------------------------------------------------------------------------"""


def src_files(d):
    p = os.path.join(REPO, d)
    out = []
    for f in sorted(os.listdir(p)):
        if f.endswith(FORT_EXT):
            out.append(f)
    return out


def obj_name(d, fname):
    base = re.sub(r"\.(f|f90|F|F90)$", "", fname)
    return f"../{d}/{base}.o"


def parse(path, fixed):
    """Return (modules_defined, modules_used, includes)."""
    mods, uses, incs = [], [], []
    with open(path, "r", errors="replace") as fh:
        for raw in fh:
            line = raw.rstrip("\n")
            # cpp includes are valid even on comment-looking lines
            m = re_cppinc.match(line)
            if m:
                incs.append(m.group(1))
                continue
            # fixed-form comment lines: c/C/* (and d/D debug) in column 1
            if fixed and line[:1] in "cC*dD!":
                continue
            # strip trailing ! comments (rough; fine for use/module/include)
            if "!" in line:
                line = line.split("!", 1)[0]
            if not line.strip():
                continue
            m = re_inc.match(line)
            if m:
                incs.append(m.group(1))
                continue
            if re_modproc.match(line) or re_endmod.match(line):
                continue
            m = re_module.match(line)
            if m:
                mods.append(m.group(1).lower())
                continue
            m = re_use.match(line)
            if m:
                uses.append(m.group(1).lower())
    return mods, uses, incs


def main():
    # Pass 1: gather every file's modules/uses/includes, build module->(dir,obj).
    file_info = {}          # (dir, fname) -> dict
    provides = {}           # dir -> {module_lower: obj}
    for d in DIR_ORDER:
        provides.setdefault(d, {})
        for f in src_files(d):
            fixed = f.endswith((".f", ".F"))
            mods, uses, incs = parse(os.path.join(REPO, d, f), fixed)
            obj = obj_name(d, f)
            file_info[(d, f)] = dict(obj=obj, mods=mods, uses=uses, incs=incs)
            for mod in mods:
                if mod in provides[d]:
                    print(f"# WARN dup module {mod} in {d}: "
                          f"{provides[d][mod]} & {obj}", file=sys.stderr)
                provides[d][mod] = obj

    all_modules = set()
    for d in provides:
        all_modules |= set(provides[d].keys())

    # Pass 2: resolve each file's dependencies.
    report_unres = []
    deps_by_dir = {}        # dir -> list of (obj, sorted_dep_list)
    for d in DIR_ORDER:
        search = [d] + INC_PATHS[d]
        entries = []
        for f in src_files(d):
            info = file_info[(d, f)]
            obj = info["obj"]
            deps = set()
            for mod in info["uses"]:
                if mod in EXTERNAL_MODULES:
                    continue
                # self-defined in same file? skip
                if mod in info["mods"]:
                    continue
                found = None
                for sd in search:
                    if mod in provides.get(sd, {}):
                        found = provides[sd][mod]
                        break
                if found is None:
                    if mod in all_modules:
                        # defined somewhere but not on this dir's search path
                        for sd in DIR_ORDER:
                            if mod in provides.get(sd, {}):
                                found = provides[sd][mod]
                                break
                        report_unres.append(
                            (obj, mod, "off-path->" + (found or "?")))
                    else:
                        report_unres.append((obj, mod, "EXTERNAL?"))
                    if found is None:
                        continue
                if found != obj:
                    deps.add(found)
            # include-file deps that live in the same dir (e.g. version.inc)
            for inc in info["incs"]:
                incbase = os.path.basename(inc)
                cand = os.path.join(REPO, d, incbase)
                # Generated includes won't be on disk in a clean tree, so don't
                # gate them on os.path.exists -- emit the same-dir dep directly.
                if os.path.exists(cand) or incbase in GENERATED_INCLUDES:
                    dep = f"../{d}/{incbase}"
                    if dep != obj:
                        deps.add(dep)
            entries.append((obj, sorted(deps)))
        deps_by_dir[d] = entries

    # Emit. This header must stay byte-for-byte identical to the committed
    # DEPENDENCIES.inc so that re-running the generator produces no spurious
    # diff (the CI deps job commits back only real changes).
    print(HEADER)
    print()
    label = {
        "equil": "Equil", "lsode": "LSODE", "zlange": "ZLANGE", "zvode": "ZVODE",
        "orbit": "Orbit", "vacuum": "Vacuum", "pentrc": "PENTRC", "dcon": "DCON",
        "rdcon": "RDCON", "stride": "STRIDE", "match": "Match", "rmatch": "Rmatch",
        "sum": "Sum", "multi": "Multi", "slayer": "SLAYER", "coil": "COIL",
        "gpec": "GPEC",
    }
    for d in DIR_ORDER:
        print(f"# {label[d]}")
        for obj, deps in deps_by_dir[d]:
            if deps:
                print(f"{obj}: {' '.join(deps)}")
        print()
    print("# XDraw")
    print("# no dependencies (C sources)")
    print()
    print("# Full project dependencies")
    print("$(ALL_OBJS): | v neededdeps")

    if report_unres:
        print("\n# ===== UNRESOLVED / CROSS-PATH NOTES (stderr) =====",
              file=sys.stderr)
        for obj, mod, note in report_unres:
            print(f"#   {obj}  uses {mod}  [{note}]", file=sys.stderr)


if __name__ == "__main__":
    main()
